import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { useState } from "react";
import { useLiTechController } from "@/core/context";

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  const [user, setUser] = useState('');
  const [controller] = useLiTechController();

  return (
    <>
      {controller.loading && (
        <div className="preloader">
          <div className="spinner"></div>
        </div>
      )}

      <div style={{ minHeight: 500 }}>{children}</div>
    </>
  );
}
