import { useCalculatorController } from "@/core/context";

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [controller] = useCalculatorController();

  return (
    <>
      {controller.loading && (
        <div className="preloader">
          <div className="spinner"></div>
        </div>
      )}
      <div
        style={{
          minHeight: 500,
        }}
      >
        {children}
      </div>
    </>
  );
}
